kind: pipeline
name: default

steps:
- name: docker  
  image: plugins/docker
  settings:
    username: docker_username
    password: docker_password
    repo: faisalavencode/droneci_react_repository
    tags: latest

