kind: pipeline
name: default
steps:
  - name: build
    image: react-dev
    settings:
      context: .
      dockerfile: Dockerfile
      volumes:
        - name: app
          path: '.:/app'
        - name: node_modules
          path: '/app/node_modules'
      tags: dev
      debug: true
      build_args:
      - NODE_ENV=development
  - name: docker
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: faisalavencode/droneci_react_repository
      tags: dev
      debug: true
