# kind: pipeline
# type: docker
# name: default
   
# steps:
# - name: test
#   image: alpine
#   commands:
#   - echo hello
#   - echo world

steps:
- name: build-alpha
  image: plugins/docker
  privileged: true
  environment:
    HOME: "/tmp"
  settings:
    repo: kazilotus/seebeez
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags: react
    debug: true
    volumes:
    - name: node_modules
      path: node_modules
  when:
    branch: main
    event: push