kind: pipeline
name: default
steps:
  - name: build
    image: node:alpine
    context: .
    dockerfile: Dockerfile
    settings:
      volumes:
        - name: app
          path: '.:/app'
        - name: node_modules
          path: '/app/node_modules'
      tags: dev
      debug: true
      build_args:
      - NODE_ENV=development
  - name: docker
    image: plugins/docker
    dockerfile: Dockerfile
    settings:
      repo: faisalavencode/droneci_react_repository
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags: dev
      debug: true
      build_args:
        - DB_HOST=database.drone-services.svc.cluster.local
        - REDIS_HOST=redis.drone-services.svc.cluster.local
        - NODE_ENV=development
      volumes:
        - name: vendor
          path: vendor
        - name: node_modules
          path: node_modules
