kind: pipeline
name: default
steps:
  - name: docker
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: faisalavencode/droneci_react_repository
      tags: dev
      debug: true
      volumes:
        - name: app
          path: '.:/app'
        - name: node_modules
          path: /app/node_modules
      environment:
        - NODE_ENV: development
        - NODE_ENV2: development2
    dockerfile: ./dockerfile